// tokens.js — theme-resolved RibbonTokens for the WebGL Ribbon (rung 2).
//
// Single source of truth for brand color in the GL path. Reads
// `window.HISD_TOKENS.ribbon` (generated by the design system) plus the active
// theme and the `--duration-slower` CSS var, and returns plain numbers the scene
// can push straight into uniforms. NEVER hardcodes brand hex except as the
// documented canonical fallback for when HISD_TOKENS is absent (SSR, token file
// not yet loaded, sandboxed embed).
//
// COLOR SPACE: returns 0..1 sRGB floats (the same space the CSS uses). No
// linearization here — the shader works in the CSS sRGB space so the live device
// matches the static SVG exactly.
//
// THE DEVICE: a SOLID brand-color FIELD with soft, low-opacity WHITE STROKES drifting
// over it. So the GL tokens that matter are: field-bg (the field color), stroke (#fff)
// and stroke-opacity (the group-level multiplier). The old from/to/highlight/fanStops
// are retained as constrained-media accents but are NOT what the GL path composites.
//
// SSR-SAFE: every `window`/`document`/`getComputedStyle` access is guarded; with no
// DOM you get the light-theme canonical fallback and flowSpeedMs = 500.

// ── Canonical fallbacks (only used when HISD_TOKENS.ribbon is unavailable) ───────
// These mirror window.HISD_TOKENS.ribbon so the GL path degrades to the right brand
// colors offline. Keep in sync with assets/hisd-tokens.js / build_tokens.py.
const FALLBACK = {
  // The canonical device: solid teal field + low-opacity white current strokes.
  fieldBg: { light: '#00A3AF', dark: '#00A3AF' },
  stroke: { light: '#FFFFFF', dark: '#FFFFFF' },
  strokeOpacity: { light: 0.16, dark: 0.22 },
  // Constrained-media accents (band/fan) — retained but not used by the GL composite.
  from: { light: '#00A3AF', dark: '#037882' },
  to: { light: '#026252', dark: '#05463C' },
  highlight: { light: '#FBDE83', dark: '#FBDE83' },
  fanStops: [
    { hex: '#00A3AF', pos: 0 },
    { hex: '#6DB83D', pos: 38 },
    { hex: '#F9D04E', pos: 64 },
    { hex: '#474F99', pos: 100 },
  ],
};

const DEFAULT_FLOW_MS = 500;

/**
 * hexToVec3(hex) -> [r, g, b]   // 0..1 sRGB floats
 *
 * Accepts '#rgb', '#rrggbb', with or without the leading '#'. Anything
 * unparseable falls back to mid-grey [0.5, 0.5, 0.5] rather than throwing, so a
 * malformed token can never crash scene bring-up.
 */
export function hexToVec3(hex) {
  if (typeof hex !== 'string') return [0.5, 0.5, 0.5];
  let h = hex.trim();
  if (h[0] === '#') h = h.slice(1);
  // Expand shorthand #rgb -> #rrggbb.
  if (h.length === 3) h = h[0] + h[0] + h[1] + h[1] + h[2] + h[2];
  if (h.length !== 6 || /[^0-9a-fA-F]/.test(h)) return [0.5, 0.5, 0.5];
  const n = parseInt(h, 16);
  return [
    ((n >> 16) & 0xff) / 255,
    ((n >> 8) & 0xff) / 255,
    (n & 0xff) / 255,
  ];
}

// Resolve a {light,dark}-keyed entry (or a bare hex string) against the theme.
function resolveThemed(entry, theme, fallbackEntry) {
  const src = entry != null ? entry : fallbackEntry;
  if (typeof src === 'string') return hexToVec3(src);
  if (src && typeof src === 'object') {
    const v = src[theme] != null ? src[theme] : src.light;
    if (v != null) return hexToVec3(v);
  }
  // Last resort: resolve the canonical fallback for this slot.
  return hexToVec3(
    typeof fallbackEntry === 'object' && fallbackEntry
      ? (fallbackEntry[theme] ?? fallbackEntry.light)
      : fallbackEntry,
  );
}

// Resolve a {light,dark}-keyed NUMBER (e.g. stroke-opacity) against the theme.
function resolveThemedNumber(entry, theme, fallbackEntry) {
  const pick = (src) => {
    if (typeof src === 'number') return src;
    if (src && typeof src === 'object') {
      const v = src[theme] != null ? src[theme] : src.light;
      if (typeof v === 'number') return v;
      const n = parseFloat(v);
      if (Number.isFinite(n)) return n;
    }
    const n = parseFloat(src);
    return Number.isFinite(n) ? n : null;
  };
  const a = pick(entry);
  if (a != null) return a;
  const b = pick(fallbackEntry);
  return b != null ? b : 0.16;
}

// Normalize a fanStops array into exactly 4 colors + 4 positions (0..1).
// fanStops entries may be hex strings or { hex, pos } objects; pos is 0..100.
function resolveFan(fanStops) {
  const stops =
    Array.isArray(fanStops) && fanStops.length ? fanStops : FALLBACK.fanStops;
  const fan = [];
  const fanPos = [];
  for (let i = 0; i < 4; i++) {
    const s = stops[i] != null ? stops[i] : stops[stops.length - 1];
    const hex = typeof s === 'string' ? s : s && s.hex;
    fan.push(hexToVec3(hex));
    // Even distribution when an explicit pos is absent.
    const rawPos =
      s && typeof s === 'object' && typeof s.pos === 'number'
        ? s.pos
        : (i / 3) * 100;
    fanPos.push(Math.max(0, Math.min(1, rawPos / 100)));
  }
  return { fan, fanPos };
}

// Read the active theme from documentElement[themeAttr]. Anything that isn't
// exactly 'dark' is treated as light (matches the design system's theming).
function resolveTheme(themeAttr) {
  try {
    if (typeof document !== 'undefined' && document.documentElement) {
      const v = document.documentElement.getAttribute(themeAttr);
      return v === 'dark' ? 'dark' : 'light';
    }
  } catch { /* no DOM */ }
  return 'light';
}

// Parse '--duration-slower' ('500ms' / '0.5s' / '500') -> milliseconds.
function resolveFlowSpeedMs() {
  try {
    if (
      typeof window !== 'undefined' &&
      typeof getComputedStyle === 'function' &&
      typeof document !== 'undefined' &&
      document.documentElement
    ) {
      const raw = getComputedStyle(document.documentElement)
        .getPropertyValue('--duration-slower')
        .trim();
      if (raw) {
        const num = parseFloat(raw);
        if (Number.isFinite(num) && num > 0) {
          // '0.5s' -> 500ms; '500ms' / '500' -> 500ms.
          return /s\s*$/.test(raw) && !/ms\s*$/.test(raw) ? num * 1000 : num;
        }
      }
    }
  } catch { /* no DOM / no computed style */ }
  return DEFAULT_FLOW_MS;
}

/**
 * readRibbonTokens(opts?) -> RibbonTokens
 *
 * opts: { themeAttr?: string }   (default 'data-theme')
 *
 * RibbonTokens = {
 *   // THE DEVICE — what the GL path composites:
 *   field:[r,g,b],            // solid field color (ribbon.field-bg, theme-resolved)
 *   stroke:[r,g,b],           // current-stroke color (ribbon.stroke, #fff)
 *   strokeOpacity:number,     // group-level stroke multiplier (theme-resolved)
 *   // constrained-media accents (retained; not used by the GL composite):
 *   from:[r,g,b], to:[r,g,b], hi:[r,g,b],   // 0..1 sRGB, theme-resolved
 *   fan:[[r,g,b] x4], fanPos:[f,f,f,f],      // fanPos in 0..1
 *   flowSpeedMs:number
 * }
 */
export function readRibbonTokens(opts = {}) {
  const themeAttr =
    opts && typeof opts.themeAttr === 'string' ? opts.themeAttr : 'data-theme';

  const theme = resolveTheme(themeAttr);

  let ribbon = null;
  try {
    if (typeof window !== 'undefined' && window.HISD_TOKENS) {
      ribbon = window.HISD_TOKENS.ribbon || null;
    }
  } catch { /* no window */ }

  const r = ribbon || {};

  // The device tokens. HISD_TOKENS may surface these as `field-bg`/`stroke`/
  // `stroke-opacity` (DTCG kebab) or `fieldBg`/`stroke`/`strokeOpacity` (JS camel);
  // accept either.
  const fieldEntry = r['field-bg'] != null ? r['field-bg'] : r.fieldBg;
  const strokeEntry = r.stroke;
  const strokeOpacityEntry =
    r['stroke-opacity'] != null ? r['stroke-opacity'] : r.strokeOpacity;

  const field = resolveThemed(fieldEntry, theme, FALLBACK.fieldBg);
  const stroke = resolveThemed(strokeEntry, theme, FALLBACK.stroke);
  const strokeOpacity = resolveThemedNumber(strokeOpacityEntry, theme, FALLBACK.strokeOpacity);

  // Constrained-media accents (retained for callers that want the band/fan).
  const from = resolveThemed(r.from, theme, FALLBACK.from);
  const to = resolveThemed(r.to, theme, FALLBACK.to);
  const hi = resolveThemed(r.highlight, theme, FALLBACK.highlight);
  const { fan, fanPos } = resolveFan(r.fanStops);

  return {
    field,
    stroke,
    strokeOpacity,
    from,
    to,
    hi,
    fan,
    fanPos,
    flowSpeedMs: resolveFlowSpeedMs(),
  };
}
