/**
 * Style Dictionary v4 configuration for HISD design tokens.
 *
 * Source of truth: ./tokens/hisd.tokens.json
 *   A verbatim copy of /.skills/design/hisd-brand-designer/assets/hisd.tokens.json (DTCG: $value / $type).
 *   Keep them in sync — re-copy when the asset is regenerated by build_tokens.py.
 *
 * DTCG support: Style Dictionary v4 reads the W3C Design Tokens format natively when
 * `usesDtcg: true` is set on a source/platform. That tells SD to look for `$value` / `$type`
 * (instead of the legacy `value` / `type`). See https://styledictionary.com/info/dtcg/.
 *
 * Outputs (all under ./build):
 *   css/hisd.variables.css       CSS custom properties (:root { --color-teal-500: ... })
 *   scss/_hisd.variables.scss    SCSS variables ($color-teal-500: ...)
 *   js/hisd.tokens.js            ES module export (flat JS object)
 *   js/hisd.tokens.d.ts          TypeScript declarations for the JS export
 *   ios/HISDColors.swift         Swift UIColor extension (iOS)
 *   ios/hisd-tokens.json         Flat JSON for iOS (fallback / non-Swift consumers)
 *   android/hisd_colors.xml      Android color resources (<color name="...">)
 *   android/hisd_dimens.xml      Android dimension resources (<dimen name="...">)
 *   figma/hisd.tokens-studio.json  Tokens Studio for Figma import (value/type shape)
 */

import StyleDictionary from 'style-dictionary';

/* -------------------------------------------------------------------------- */
/*  Custom format: Tokens Studio for Figma                                    */
/*                                                                            */
/*  Tokens Studio expects the legacy single-file shape with `value` / `type`  */
/*  (no `$`), nested groups preserved, references written as {group.token}.   */
/*  Style Dictionary's DTCG tokens carry `$value`/`$type`; we walk the        */
/*  original (unresolved) token tree and rewrite the keys + map DTCG `$type`  */
/*  values to the Tokens Studio type vocabulary.                              */
/* -------------------------------------------------------------------------- */

// DTCG $type  ->  Tokens Studio type
const TOKENS_STUDIO_TYPE = {
  color: 'color',
  dimension: 'dimension',
  fontFamily: 'fontFamilies',
  fontWeight: 'fontWeights',
  number: 'number',
  duration: 'duration',
  cubicBezier: 'cubicBezier',
  shadow: 'boxShadow',
};

function isDtcgToken(node) {
  return node && typeof node === 'object' && '$value' in node;
}

function toTokensStudio(node) {
  if (isDtcgToken(node)) {
    const type = node.$type;
    const out = {
      value: node.$value,
      type: TOKENS_STUDIO_TYPE[type] || type || 'other',
    };
    if (node.$description) out.description = node.$description;
    return out;
  }
  const out = {};
  for (const [key, child] of Object.entries(node)) {
    if (key.startsWith('$')) continue; // skip group-level $description etc.
    out[key] = toTokensStudio(child);
  }
  return out;
}

StyleDictionary.registerFormat({
  name: 'figma/tokens-studio',
  format: ({ dictionary }) => {
    // dictionary.tokens is the resolved-but-still-nested token object (DTCG keys).
    const studio = toTokensStudio(dictionary.tokens);
    studio.$themes = [];
    studio.$metadata = {
      tokenSetOrder: ['global'],
    };
    // Tokens Studio single-file import wraps everything in one set named "global".
    const { $themes, $metadata, ...sets } = studio;
    return JSON.stringify({ global: sets, $themes, $metadata }, null, 2) + '\n';
  },
});

/* -------------------------------------------------------------------------- */
/*  Filters — split dimension-ish vs color tokens for Android resources.      */
/* -------------------------------------------------------------------------- */

const isColor = (token) => token.$type === 'color' || token.type === 'color';
const isDimension = (token) => {
  const t = token.$type || token.type;
  return t === 'dimension';
};

StyleDictionary.registerFilter({
  name: 'isColor',
  filter: isColor,
});
StyleDictionary.registerFilter({
  name: 'isDimension',
  filter: isDimension,
});

/* -------------------------------------------------------------------------- */
/*  Config                                                                     */
/* -------------------------------------------------------------------------- */

export default {
  // Read DTCG tokens ($value / $type).
  source: ['tokens/hisd.tokens.json'],
  // Top-level flag is inherited by every platform below.
  // (Set again per-platform if you ever mix DTCG and legacy sources.)
  log: {
    // SD warns about "token collisions" when leaf names repeat across groups
    // (e.g. space.0 / dataviz.categorical.0 / elevation.light.0). Those are
    // distinct, fully-pathed tokens in every output we emit — the warning is a
    // false positive from SD's flat-name heuristic. Keep the build output clean.
    warnings: 'disabled',
  },
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'build/css/',
      options: { usesDtcg: true },
      files: [
        {
          destination: 'hisd.variables.css',
          format: 'css/variables',
          options: { outputReferences: true },
        },
      ],
    },

    scss: {
      transformGroup: 'scss',
      buildPath: 'build/scss/',
      options: { usesDtcg: true },
      files: [
        {
          destination: '_hisd.variables.scss',
          format: 'scss/variables',
          options: { outputReferences: true },
        },
      ],
    },

    js: {
      transformGroup: 'js',
      buildPath: 'build/js/',
      options: { usesDtcg: true },
      files: [
        {
          destination: 'hisd.tokens.js',
          format: 'javascript/es6',
        },
        {
          destination: 'hisd.tokens.d.ts',
          format: 'typescript/es6-declarations',
        },
      ],
    },

    ios: {
      transformGroup: 'ios-swift',
      buildPath: 'build/ios/',
      options: { usesDtcg: true },
      files: [
        {
          destination: 'HISDColors.swift',
          format: 'ios-swift/class.swift',
          filter: 'isColor',
          // className + accessControl are read from file.options by this format.
          options: {
            className: 'HISDColors',
            accessControl: 'public',
          },
        },
      ],
    },

    // Raw-value JSON for iOS / tooling consumers that don't want Swift UIColor
    // strings. No Swift transform group, so values stay as hex / rem / ms etc.
    // NOTE: must use the NESTED `json` format, not `json/flat`. json/flat keys
    // on the leaf name only, so repeated leaves (space.0, dataviz.categorical.0,
    // elevation.light.0 …) collide and silently drop tokens. Nested keeps all.
    'ios-json': {
      buildPath: 'build/ios/',
      options: { usesDtcg: true },
      files: [
        {
          destination: 'hisd-tokens.json',
          format: 'json',
        },
      ],
    },

    android: {
      transformGroup: 'android',
      buildPath: 'build/android/',
      options: { usesDtcg: true },
      files: [
        {
          destination: 'hisd_colors.xml',
          format: 'android/colors',
          filter: 'isColor',
        },
        {
          destination: 'hisd_dimens.xml',
          format: 'android/dimens',
          filter: 'isDimension',
        },
      ],
    },

    figma: {
      // No transforms — Tokens Studio wants raw token values, not platform-massaged ones.
      buildPath: 'build/figma/',
      options: { usesDtcg: true },
      files: [
        {
          destination: 'hisd.tokens-studio.json',
          format: 'figma/tokens-studio',
        },
      ],
    },
  },
};
