#!/usr/bin/env python3
"""Bundle the HISD component library and generate its gallery.

  - components/components.css : every component stylesheet concatenated, so a
    consumer can link ONE file (after hisd-theme.css) and use any component.
  - components/index.html     : an on-brand gallery linking every live demo,
    grouped by category, with a light/dark toggle. Dogfoods the components.

Run after adding/editing a component:  python3 build_components.py
"""
import os, glob

HERE = os.path.dirname(os.path.abspath(__file__))
DIR = os.path.normpath(os.path.join(HERE, "..", "components"))

# name -> (category, one-line description). Order within a category is intentional.
CATALOG = [
    ("Forms & inputs", [
        ("button", "Four intent variants — action, secondary, ghost, danger — with loading state."),
        ("input-text", "Text field with label-above, helper text, and an error state wired via aria-describedby."),
        ("textarea", "Multi-line input sharing the field shell; vertical resize only."),
        ("select", "Native select with a tokenized custom chevron and the shared focus/error shell."),
        ("selection-controls", "Custom-styled checkbox and radio (grouped in a fieldset)."),
        ("switch", "role=switch toggle with a perceivable OFF-state boundary."),
        ("theme-toggle", "Icon-only light/dark control with aria-pressed state."),
    ]),
    ("Navigation", [
        ("navbar", "Top navigation with a skip-link, current-page accent, and a mobile drawer."),
        ("sidebar", "Sidebar navigation with grouped sections and an inline-start active rail."),
        ("tabs", "APG tabs — roving focus, arrow-key activation, overflow scroll."),
        ("breadcrumb", "Breadcrumb trail with aria-current on the leaf and presentational separators."),
        ("pagination", "Page navigation with prev/next bounds, ellipsis, and aria-current."),
    ]),
    ("Feedback & status", [
        ("alert", "Inline banner in four semantic variants — meaning carried by icon + text, not color."),
        ("toast", "Live-region toasts that stack, auto-dismiss, and use the status token set."),
        ("tooltip", "Hover/focus label wired via aria-describedby; never the sole label."),
        ("progress", "Determinate bar (role=progressbar) and a reduced-motion-safe indeterminate variant."),
        ("skeleton", "Loading placeholders with a paused-under-reduce sheen, the opacity crossfade, and a CLS-proof media frame."),
        ("badge", "Count and status markers; labelled when they carry information alone."),
    ]),
    ("Content & containers", [
        ("card", "Surface container; raised with shadow in light, strengthened border in dark."),
        ("chip", "Filter/selection tag; selected state carries ink on the yellow fill."),
        ("table", "Data table with zebra rows, sortable headers (aria-sort), and a scroll region."),
        ("accordion", "Disclosure pattern with aria-expanded headers and labelled panels."),
        ("avatar", "Image or initials fallback, sizes, and an optional accessible status dot."),
        ("modal", "Blocking dialog with focus trap; destructive variant uses role=alertdialog."),
        ("map", "Accessible map shell — DOM list is source of truth; renderer (MapLibre/ArcGIS) plugs into the canvas."),
        ("ribbon", "Animated bayou ribbon graphic device — a gradient band with a compositor-only drift, guarded under reduced-motion and forced-colors."),
    ]),
]

LOGO = "../assets/logos/full-logo/full-dark-grey-teal.svg"
LOGO_DARK = "../assets/logos/full-logo/full-white.svg"


def bundle_css():
    files = sorted(glob.glob(os.path.join(DIR, "*.css")))
    files = [f for f in files if os.path.basename(f) != "components.css"]
    parts = ["/* HISD component library — bundled. Generated by build_components.py.",
             "   Link AFTER hisd-theme.css. Do not edit by hand; edit the per-component",
             "   stylesheet and re-run the build. */", ""]
    for f in files:
        name = os.path.basename(f)
        parts.append(f"/* ===== {name} ===== */")
        parts.append(open(f).read().rstrip())
        parts.append("")
    out = os.path.join(DIR, "components.css")
    with open(out, "w") as fh:
        fh.write("\n".join(parts) + "\n")
    return len(files), out


def gallery():
    cards = []
    total = 0
    for category, items in CATALOG:
        rows = []
        for name, desc in items:
            total += 1
            rows.append(
                f'      <a class="hisd-card g-card" href="{name}.html">\n'
                f'        <span class="g-name">{name}</span>\n'
                f'        <span class="g-desc">{desc}</span>\n'
                f'      </a>')
        cards.append(
            f'    <section class="g-section">\n'
            f'      <h2>{category}</h2>\n'
            f'      <div class="g-grid">\n' + "\n".join(rows) + "\n      </div>\n    </section>")
    body = "\n".join(cards)
    html = f"""<!doctype html>
<html lang="en" data-theme-source="system">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>HISD Component Library</title>
<link rel="stylesheet" href="../assets/hisd-theme.css">
<link rel="stylesheet" href="components.css">
<style>
  body{{margin:0;background:var(--color-bg);color:var(--color-text);font-family:var(--font-sans);line-height:var(--leading-normal)}}
  header{{display:flex;align-items:center;gap:var(--space-3);padding:var(--space-5) var(--space-6);
         background:var(--color-brand);color:var(--color-on-action)}}
  header img{{height:2rem;width:auto}} .logo-dark{{display:none}}
  [data-theme="dark"] .logo-light{{display:none}} [data-theme="dark"] .logo-dark{{display:inline}}
  header h1{{font-family:var(--font-display);font-size:var(--text-xl);margin:0}}
  .toggle{{margin-inline-start:auto;font:inherit;font-weight:600;border:none;border-radius:var(--radius-pill);
          padding:var(--space-2) var(--space-4);background:var(--color-surface);color:var(--color-text);cursor:pointer}}
  .toggle:focus-visible{{outline:2px solid var(--color-on-action);outline-offset:2px}}
  main{{max-width:1080px;margin:0 auto;padding:var(--space-8) var(--space-6)}}
  .lede{{font-family:var(--font-serif);font-size:var(--text-lg);color:var(--color-text-muted);max-width:60ch}}
  .g-section{{margin-block-start:var(--space-10)}}
  .g-section h2{{font-family:var(--font-display);color:var(--color-brand);font-size:var(--text-2xl);
                border-block-end:2px solid var(--color-border);padding-block-end:var(--space-2)}}
  .g-grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));gap:var(--space-4);margin-block-start:var(--space-5)}}
  .g-card{{display:flex;flex-direction:column;gap:var(--space-2);text-decoration:none;color:inherit}}
  .g-card:hover{{box-shadow:var(--shadow-3)}}
  .g-card:focus-visible{{outline:2px solid var(--color-focus);outline-offset:2px}}
  .g-name{{font-family:var(--font-display);font-weight:700;color:var(--color-action);font-size:var(--text-lg)}}
  .g-desc{{color:var(--color-text-muted);font-size:var(--text-sm)}}
  footer{{max-width:1080px;margin:0 auto;padding:var(--space-8) var(--space-6);color:var(--color-text-subtle);font-size:var(--text-sm)}}
</style></head>
<body>
<header>
  <img class="logo-light" src="{LOGO}" alt="Houston ISD">
  <img class="logo-dark" src="{LOGO_DARK}" alt="Houston ISD">
  <h1>Component Library</h1>
  <button class="toggle" onclick="var h=document.documentElement;h.dataset.theme=(h.dataset.theme==='dark'?'light':'dark')">Toggle theme</button>
</header>
<main>
  <p class="lede">{total} accessible, themeable components built on the HISD "Connected Futures" design system.
  Every component paints color only through semantic tokens, ships a visible focus ring, and works in light and dark.
  Open any demo to see all states in both themes with a copy-paste snippet.</p>
{body}
</main>
<footer>Generated by <code>scripts/build_components.py</code> · styles in <code>components/components.css</code> ·
verified by <code>scripts/lint_components.py</code> and the contrast gate in <code>scripts/build_tokens.py</code>.</footer>
</body></html>
"""
    out = os.path.join(DIR, "index.html")
    with open(out, "w") as fh:
        fh.write(html)
    return total, out


if __name__ == "__main__":
    n, css = bundle_css()
    t, idx = gallery()
    # sanity: every catalogued component has a demo + stylesheet
    cataloged = {name for _, items in CATALOG for name, _ in items}
    have = {os.path.splitext(os.path.basename(f))[0] for f in glob.glob(os.path.join(DIR, "*.html"))
            if os.path.basename(f) != "index.html"}
    missing = cataloged - have
    extra = have - cataloged
    print(f"Bundled {n} stylesheets -> {os.path.basename(css)}")
    print(f"Gallery: {t} components -> {os.path.basename(idx)}")
    if missing:
        print("WARNING: catalogued but no demo:", ", ".join(sorted(missing)))
    if extra:
        print("WARNING: demo exists but not in gallery catalog:", ", ".join(sorted(extra)))
