#!/usr/bin/env python3
"""Emit the skill's brand-assets.json from its OWN vendored assets.

The skill is self-contained: this reads the logos/fonts vendored under
.skills/design/hisd-brand-designer/assets/ (by catalog_assets.py) and writes
assets/brand-assets.json with paths relative to the skill root, so the skill
works dropped into any repo with no external dependency.

Run:  python3 make_asset_manifest.py
"""
import os, json, glob

HERE = os.path.dirname(os.path.abspath(__file__))
SKILL = os.path.normpath(os.path.join(HERE, ".."))          # the skill root
ASSETS = os.path.join(SKILL, "assets")
LOGOS = os.path.join(ASSETS, "logos")
OUT = os.path.join(ASSETS, "brand-assets.json")

def rel(p):
    return os.path.relpath(p, SKILL)

def pick(group, *names):
    out = [rel(p) for n in names for p in [os.path.join(LOGOS, group, f"{n}.svg")] if os.path.exists(p)]
    return out or [rel(p) for p in sorted(glob.glob(os.path.join(LOGOS, group, "*.svg")))[:4]]

def group_index():
    idx = {}
    if not os.path.isdir(LOGOS):
        return idx
    for g in sorted(os.listdir(LOGOS)):
        gp = os.path.join(LOGOS, g)
        if not os.path.isdir(gp):
            continue
        svgs = glob.glob(os.path.join(gp, "**", "*.svg"), recursive=True)
        subs = sorted(d for d in os.listdir(gp) if os.path.isdir(os.path.join(gp, d)))
        idx[g] = {"svg_count": len(svgs), "subjects": subs}
    return idx

PALETTE = {"teal": "#00A3AF", "dark-green": "#006F5B", "light-green": "#6DB83D",
           "yellow": "#F9D04E", "purple": "#474F99", "blue": "#4975BD", "red": "#D96364",
           "dark-grey": "#24383C", "light-grey": "#D4D4D5", "off-white": "#FFFFED"}

manifest = {
    "_note": "Generated by make_asset_manifest.py from the skill's vendored assets. Paths are relative to the skill root (.skills/design/hisd-brand-designer/). The skill is self-contained — no external dependency.",
    "quick": {  # the marks you reach for most
        "logo_on_light": pick("full-logo", "full-dark-grey-teal", "full-dark-grey"),
        "logo_on_dark":  pick("full-logo", "full-white") + pick("submark", "horizontal-white-yellow"),
        "icon":          pick("icon", "teal", "white"),
        "seal":          pick("seal", "flat-full-color", "flat-teal"),
    },
    "logo_groups": group_index(),
    "fonts": {"variable_web_fonts": sorted(rel(p) for p in glob.glob(os.path.join(ASSETS, "fonts", "*VariableFont*.ttf"))),
              "roles": {"sans_ui_body": "Radio Canada", "display_headlines": "Parkinsans",
                        "serif_editorial": "Lora", "fallbacks": ["Arial", "Times New Roman"]}},
    "palette": PALETTE,
    "tokens": {"css": "assets/hisd-theme.css", "dtcg_json": "assets/hisd.tokens.json",
               "scss": "assets/hisd-tokens.scss", "powerbi_theme": "assets/hisd-powerbi-theme.json",
               "style_guide": "assets/style-guide.html", "contrast_report": "assets/contrast-report.md"},
    "full_catalog_in_repo": "Artifacts/Brand-Assets/CATALOG.md (this repo only; the skill vendors the same logos under assets/logos/)",
}

with open(OUT, "w") as f:
    json.dump(manifest, f, indent=2)

print("Wrote", rel(OUT))
print("  logo groups:", {g: v["svg_count"] for g, v in manifest["logo_groups"].items()})
print("  variable web fonts vendored:", len(manifest["fonts"]["variable_web_fonts"]))
