#!/usr/bin/env python3
"""Project the canonical skill into thin vendor-lane pointer adapters.

Per the Lamplighter skill model (Skill-Adapter + Vendor-Lanes): the canonical
SKILL.md + scripts + assets live once under `.skills/<skill>/`; each lane consumes
a THIN POINTER that references the canonical body and NEVER copies it. This is the
projection step that emits those adapters (generated, never hand-edited) plus a
`--check` drift mode.

Lanes projected (per Vendor-Lanes.md exact surfaces):
  native:
    - claude-code : .claude/skills/<name>/SKILL.md            (instruction surface CLAUDE.md)
    - codex       : .agents/skills/<name>/SKILL.md + agents/openai.yaml   (AGENTS.md;
                    .codex/hooks.json is for hooks, of which this skill has none)
  guidance (opt-in; authorized for this skill):
    - copilot     : .github/agents/<name>.agent.md            (.github/copilot-instructions.md)
    - gemini      : .gemini/extensions/<name>/{gemini-extension.json,GEMINI.md}

The assistant ZIP lanes (Claude.ai / OpenAI dev-API) are NOT projected: at 155 MB /
1,310 files the skill exceeds their 50 MB / 500-file budget — a limit that binds a
full-copy zip, not a thin adapter.

Installing into ANOTHER repo requires this projection too: copy the canonical
`.skills/<name>/` into the target repo, then run `project_adapters.py --apply` there
to generate that repo's adapters.

    python3 project_adapters.py            # dry-run plan
    python3 project_adapters.py --apply    # write the adapters
    python3 project_adapters.py --check    # drift: do the adapters still match canonical?
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SKILL_DIR = os.path.normpath(os.path.join(HERE, ".."))          # .skills/<...>/<name>
NAME = os.path.basename(SKILL_DIR)
CANON_SKILL_MD = os.path.join(SKILL_DIR, "SKILL.md")


def _find_repo_root(start):
    """Walk up from `start` to find the repo root (a dir containing .git).
    Works for both flat (`.skills/<name>/`) and family-grouped (`.skills/<family>/<name>/`)
    canonical layouts so the projector is portable across host repos."""
    cur = start
    for _ in range(20):
        if os.path.exists(os.path.join(cur, ".git")):
            return cur
        parent = os.path.dirname(cur)
        if parent == cur:
            break
        cur = parent
    # Fallback: assume flat layout (skills/<name> two levels under repo root).
    return os.path.normpath(os.path.join(SKILL_DIR, "..", ".."))


REPO = _find_repo_root(SKILL_DIR)
# Canonical path expressed relative to the repo root, for the adapter pointers.
CANON_REL = os.path.relpath(CANON_SKILL_MD, REPO).replace(os.sep, "/")
CANON_DIR_REL = os.path.dirname(CANON_REL)

# Each lane lists (format, repo-relative-path). Formats are rendered below.
LANES = {
    "claude-code": {"surface": "CLAUDE.md", "files": [
        ("pointer-md", ".claude/skills/%s/SKILL.md" % NAME)]},
    "codex": {"surface": "AGENTS.md", "files": [
        ("pointer-md", ".agents/skills/%s/SKILL.md" % NAME),
        ("openai-yaml", "agents/openai.yaml")]},
    "copilot": {"surface": ".github/copilot-instructions.md", "files": [
        ("agent-md", ".github/agents/%s.agent.md" % NAME)]},
    "gemini": {"surface": "GEMINI.md", "files": [
        ("gemini-json", ".gemini/extensions/%s/gemini-extension.json" % NAME),
        ("pointer-md", ".gemini/extensions/%s/GEMINI.md" % NAME)]},
}


def _canonical():
    text = open(CANON_SKILL_MD, encoding="utf-8").read()
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    name = NAME
    if m:
        nm = re.search(r"^name:\s*(.+)$", m.group(1), re.M)
        if nm:
            name = nm.group(1).strip()
    dm = re.search(r"description:\s*>-?\s*\n((?:[ \t]+.*\n)+)", text)
    desc = re.sub(r"\s+", " ", dm.group(1)).strip() if dm else name
    ver = "0.0.0"
    vm = os.path.join(SKILL_DIR, "versioning", "version.manifest.json")
    if os.path.exists(vm):
        ver = json.load(open(vm)).get("version", ver)
    return name, desc, ver


def _rel_to_canon(dest_abs):
    return os.path.relpath(CANON_SKILL_MD, os.path.dirname(dest_abs)).replace(os.sep, "/")


def _provenance(lane, ver):
    return ("Provenance: canonical `%s` · lane `%s` · v%s. "
            "Generated by `%s/scripts/project_adapters.py` — do not edit; "
            "regenerate after any canonical change."
            % (CANON_REL, lane, ver, CANON_DIR_REL))


def _body(lane, ver, rel):
    return ("> **Generated thin adapter — don't hand-edit this file.** Edit the\n"
            "> canonical body at `%s/` instead, then regenerate the adapters with\n"
            "> `python3 %s/scripts/project_adapters.py --apply`. The canonical body\n"
            "> in this repo IS meant to evolve as you use the skill — improvements\n"
            "> flow upstream to `Wonder-Forge/HISD_Design`.\n\n"
            "This is a pointer, not a copy. The authoritative SKILL.md, scripts, and\n"
            "assets live at [`%s`](%s) (canonical `%s/`). **Read and follow that\n"
            "file**; its body is resolved from there and never duplicated here.\n\n%s\n"
            % (CANON_DIR_REL, CANON_DIR_REL, rel, rel, CANON_DIR_REL,
               _provenance(lane, ver)))


def render(fmt, lane, dest_abs, name, desc, ver):
    rel = _rel_to_canon(dest_abs)
    if fmt in ("pointer-md", "agent-md"):
        front = ("---\nname: %s\ndescription: >-\n  %s\nmetadata:\n  source: adapter\n"
                 "  lane: %s\n  version: %s\n  canonical: %s\n"
                 "  generated-by: %s/scripts/project_adapters.py\n---\n\n"
                 % (name, desc, lane, ver, CANON_REL, CANON_DIR_REL))
        title = "# %s — %s pointer adapter (generated)\n\n" % (name, lane)
        return front + title + _body(lane, ver, rel)
    if fmt == "openai-yaml":
        return ("# Codex vendor config for the %s skill (generated adapter).\n"
                "# The canonical skill lives at %s/ ; this declares the Codex interface only.\n"
                "interface:\n  name: %s\n  entrypoint: .agents/skills/%s/SKILL.md\n"
                "policy:\n  allow_implicit_invocation: true\ndependencies:\n  tools: []\n"
                % (name, CANON_DIR_REL, name, NAME))
    if fmt == "gemini-json":
        return json.dumps({
            "name": name,
            "version": ver,
            "description": desc[:200],
            "contextFileName": "GEMINI.md",
            "_generated": "scripts/project_adapters.py (thin pointer adapter)",
        }, indent=2) + "\n"
    raise ValueError("unknown format " + fmt)


def main(argv):
    apply = "--apply" in argv
    check = "--check" in argv
    name, desc, ver = _canonical()
    drift, planned = [], []
    for lane, spec in LANES.items():
        for fmt, relpath in spec["files"]:
            dest = os.path.join(REPO, relpath)
            want = render(fmt, lane, dest, name, desc, ver)
            have = open(dest, encoding="utf-8").read() if os.path.exists(dest) else None
            status = "up-to-date" if have == want else ("create" if have is None else "update")
            if check:
                if status != "up-to-date":
                    drift.append("%s: %s is %s vs canonical" % (lane, relpath, status))
                continue
            planned.append((lane, relpath, status))
            print("  [%s] %s: %s (%s)" % (lane, "write" if apply else "plan", relpath, status))
            if apply:
                os.makedirs(os.path.dirname(dest), exist_ok=True)
                with open(dest, "w", encoding="utf-8") as fh:
                    fh.write(want)
    if check:
        if drift:
            print("ADAPTER DRIFT:")
            for d in drift:
                print("  -", d)
            return 1
        print("All %d adapter files are in sync with the canonical skill." %
              sum(len(s["files"]) for s in LANES.values()))
        return 0
    if not apply:
        print("\nDry run. Re-run with --apply to write the adapters.")
    else:
        lanes = ", ".join(LANES)
        print("\nProjected %s v%s -> %s." % (name, ver, lanes))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
